### PR TITLE
showing the toc on all pages but the home page

### PR DESCRIPTION
**Pull request by adelegard**
Also adjusting some footer font styling.

### CODE REVIEW

**Comment by unparalleled-js** [comment]
I see it on all the guides but not on the API docs.

**Comment by adelegard** [comment]
> I see it on all the guides but not on the API docs.

This is correct. The API documentation has its own left side nav.

**Comment by unparalleled-js** [comment]
Screen Shot 2020-12-14 at 21 22 35

Is this the home page? Is the goal to not be showing this here?  There is also a lot of white space underneath it.

**Comment by adelegard** [comment]
> Screen Shot 2020-12-14 at 21 22 35
> 
> Is this the home page? Is the goal to not be showing this here? There is also a lot of white space underneath it.

Yes. The goal of this PR is to hide the left nav on just this page. And yes there is a lot of whitespace. We'll adjust the styling of this at a later date.

**Review by unparalleled-js — APPROVED** [review]

**Review by alanag13 — APPROVED** [review]

**Comment by alanag13** [comment]
@unparalleled-js I think you were maybe confusing `toc` (table of contents) with `tos` (terms of service).

**Comment by unparalleled-js** [comment]
> @unparalleled-js I think you were maybe confusing `toc` (table of contents) with `tos` (terms of service).

Haha yes

**Pull request merged**
